// AUTO-GENERATED by scripts (events-payload)

import type { ServerExecutionFlowFunctionsWithVars } from '../runtime/core.js'
import type { VariablesDefinition } from '../runtime/variables.js'
import type { ServerEventPayloads } from './events-payload.js'

export interface ServerOnOverloads<
  Vars extends VariablesDefinition,
  F extends ServerExecutionFlowFunctionsWithVars<Vars> = ServerExecutionFlowFunctionsWithVars<Vars>
> {
  /**
   * This event is triggered when a Node Graph Variable in the current Node Graph changes; The previous and current values are Generic. Determine the Generic type to correctly receive events for Node Graph Variables of the corresponding type; Vessel-type Node Graph Variables do not provide before-value and after-value Output Parameters
   *
   * 节点图变量变化时: 当前节点图的节点图变量发生变化时，触发该事件; 注意变化前值和变化后值为泛型，需确定其泛型类型后，才能正确接收到对应类型节点图变量的事件; 容器类型的节点图变量没有变化前值和变化后值出参
   */
  on(
    eventName: 'whenNodeGraphVariableChanges',
    handler: (evt: ServerEventPayloads['whenNodeGraphVariableChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when the Custom Variable of the Entity associated with the current Node Graph changes; The previous and current values are Generic. Determine the Generic type before you can correctly receive events for Custom Variables of the corresponding type; Vessel-type Custom Variables do not provide before-value and after-value Output Parameters
   *
   * 自定义变量变化时: 当前节点图所关联实体的自定义变量发生变化时，触发该事件; 注意变化前值和变化后值为泛型，需确定其泛型类型后，才能正确接收到对应类型自定义变量的事件; 容器类型的自定义变量没有变化前值和变化后值出参
   */
  on(
    eventName: 'whenCustomVariableChanges',
    handler: (evt: ServerEventPayloads['whenCustomVariableChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when the Preset Status of the Entity associated with the Node Graph changes
   *
   * 预设状态变化时: 节点图所关联的实体的预设状态发生变化时，触发该事件
   */
  on(
    eventName: 'whenPresetStatusChanges',
    handler: (evt: ServerEventPayloads['whenPresetStatusChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when the preset state of a complex creation is changed using the "Set the preset status
   * value of the complex creation" node (the modified and unmodified values must be different for this event to
   * trigger).; This node graph event can only be received by the node graph of the complex creation.
   *
   * 复杂造物预设状态变化时: 使用“设置复杂造物预设状态值”节点更改复杂造物预设状态时触发（修改前后值需不同才触发）；该事件仅复杂造物节点图可接收
   */
  on(
    eventName: 'whenComplexCreationPresetStatusChanges',
    handler: (evt: ServerEventPayloads['whenComplexCreationPresetStatusChanges'], f: F) => void
  ): this

  /**
   * Adds the Unit Status effect [Monitor Movement Speed] to the Character Entity. This event is triggered when the conditions are met
   *
   * 角色移动速度达到条件时: 为角色实体添加单位状态效果【监听移动速率】，达成条件会触发该事件
   */
  on(
    eventName: 'whenCharacterMovementSpdMeetsCondition',
    handler: (evt: ServerEventPayloads['whenCharacterMovementSpdMeetsCondition'], f: F) => void
  ): this

  /**
   * This event is triggered when an Entity is created; All types of Entities can trigger this event. Stage Entities, Character Entities, and Player Entities trigger this event when entering a Stage
   *
   * 实体创建时: 实体被创建时，触发该事件; 所有类型的实体均可以触发该事件。关卡实体、角色实体和玩家实体会在进入关卡时触发该事件
   */
  on(
    eventName: 'whenEntityIsCreated',
    handler: (evt: ServerEventPayloads['whenEntityIsCreated'], f: F) => void
  ): this

  /**
   * This event triggers when objects and creations within the stage are destroyed. This event can only trigger on stage entities.
   *
   * 实体销毁时: 关卡内物件和造物被销毁时触发该事件，该事件仅在关卡实体上可以触发
   */
  on(
    eventName: 'whenEntityIsDestroyed',
    handler: (evt: ServerEventPayloads['whenEntityIsDestroyed'], f: F) => void
  ): this

  /**
   * This event is triggered when any Entity in the Stage is removed or destroyed, and it can only be triggered on Stage Entities; This event is triggered upon Entity destruction or removal. Therefore, when an Entity is destroyed, it triggers both the [On Entity Destroyed] and [On Entity Removed/Destroyed] events in sequence
   *
   * 实体移除/销毁时: 关卡内任意实体被移除或销毁时触发该事件，该事件仅在关卡实体上可以触发; 实体被销毁或被移除均会触发该事件。因此实体被销毁时，会依次触发【实体销毁时】以及【实体移除/销毁时】事件
   */
  on(
    eventName: 'whenEntityIsRemovedDestroyed',
    handler: (evt: ServerEventPayloads['whenEntityIsRemovedDestroyed'], f: F) => void
  ): this

  /**
   * This event is triggered when an Entity's Faction changes
   *
   * 实体阵营变化时: 实体的阵营变化时，触发该事件
   */
  on(
    eventName: 'whenEntityFactionChanges',
    handler: (evt: ServerEventPayloads['whenEntityFactionChanges'], f: F) => void
  ): this

  /**
   * When a Character is Downed, the Node Graph on the Character Entity can trigger this event
   *
   * 角色倒下时: 角色倒下时，角色实体上的节点图可以触发该事件
   */
  on(
    eventName: 'whenTheCharacterIsDown',
    handler: (evt: ServerEventPayloads['whenTheCharacterIsDown'], f: F) => void
  ): this

  /**
   * When a Character is Revived, the Node Graph on the Character Entity can trigger this event
   *
   * 角色复苏时: 角色复苏时，角色实体上的的节点图可以触发该事件
   */
  on(
    eventName: 'whenCharacterRevives',
    handler: (evt: ServerEventPayloads['whenCharacterRevives'], f: F) => void
  ): this

  /**
   * This event is triggered on the Player Entity's Node Graph when the Player completes teleportation; This event is also triggered when a Player enters a Stage for the first time
   *
   * 玩家传送完成时: 玩家传送完成时，在玩家实体的节点图上可以触发该事件
   */
  on(
    eventName: 'whenPlayerTeleportCompletes',
    handler: (evt: ServerEventPayloads['whenPlayerTeleportCompletes'], f: F) => void
  ): this

  /**
   * This event is triggered on the Player Entity's Node Graph when all of the Player's Character Entities are Downed
   *
   * 玩家所有角色倒下时: 玩家的所有角色实体均倒下时，玩家实体的节点图上触发该事件
   */
  on(
    eventName: 'whenAllPlayerSCharactersAreDown',
    handler: (evt: ServerEventPayloads['whenAllPlayerSCharactersAreDown'], f: F) => void
  ): this

  /**
   * This event is triggered on the Player Entity's Node Graph when all of the Player's Characters are Revived
   *
   * 玩家所有角色复苏时: 玩家的所有角色均复苏时，玩家实体的节点图触发该事件
   */
  on(
    eventName: 'whenAllPlayerSCharactersAreRevived',
    handler: (evt: ServerEventPayloads['whenAllPlayerSCharactersAreRevived'], f: F) => void
  ): this

  /**
   * This event is triggered on the Player Entity when a Character is Downed and then Revived due to drowning, falling into an abyss, or similar reasons
   *
   * 玩家异常倒下并复苏时: 角色因溺水、坠入深渊等原因倒下并复苏时，玩家实体上触发该事件
   */
  on(
    eventName: 'whenPlayerIsAbnormallyDownedAndRevives',
    handler: (evt: ServerEventPayloads['whenPlayerIsAbnormallyDownedAndRevives'], f: F) => void
  ): this

  /**
   * Available only in Classic Mode. This event is triggered on the player entity when the active character changes.
   *
   * 前台角色变化时: 仅经典模式可用，前台角色变化时在玩家实体上触发该事件
   */
  on(
    eventName: 'whenTheActiveCharacterChanges',
    handler: (evt: ServerEventPayloads['whenTheActiveCharacterChanges'], f: F) => void
  ): this

  /**
   * The "Collision Trigger Source" range of a runtime entity A enters the "Collision Trigger" range of another runtime entity B; Node graph events will be sent to the entity B configured with "Collision Trigger"
   *
   * 进入碰撞触发器时: 运行中实体A的”碰撞触发源“范围，进入其他运行中实体B的“碰撞触发器”范围。; 会发送节点图事件给配置“碰撞触发器”的实体B
   */
  on(
    eventName: 'whenEnteringCollisionTrigger',
    handler: (evt: ServerEventPayloads['whenEnteringCollisionTrigger'], f: F) => void
  ): this

  /**
   * When the "Collision Trigger Source" range of active Entity A leaves the "Collision Trigger" range of active Entity B; Node graph events will be sent to the entity B configured with "Collision Trigger"
   *
   * 离开碰撞触发器时: 运行中实体A的“碰撞触发源”范围，离开其他运行中实体B的“碰撞触发器”范围; 会发送节点图事件给配置“碰撞触发器”的实体B
   */
  on(
    eventName: 'whenExitingCollisionTrigger',
    handler: (evt: ServerEventPayloads['whenExitingCollisionTrigger'], f: F) => void
  ): this

  /**
   * This event is triggered when an Entity's HP is restored
   *
   * 被恢复生命值时: 实体被恢复生命值时，触发该事件
   */
  on(
    eventName: 'whenHpIsRecovered',
    handler: (evt: ServerEventPayloads['whenHpIsRecovered'], f: F) => void
  ): this

  /**
   * This event is triggered on the initiating Entity when an Entity restores HP to other Entities
   *
   * 发起恢复生命值时: 实体向其他实体恢复生命值时，发起者实体上触发该事件
   */
  on(
    eventName: 'whenInitiatingHpRecovery',
    handler: (evt: ServerEventPayloads['whenInitiatingHpRecovery'], f: F) => void
  ): this

  /**
   * This event is triggered when an Entity's attack hits other Entities
   *
   * 攻击命中时: 实体的攻击命中其他实体时，触发该事件
   */
  on(
    eventName: 'whenAttackHits',
    handler: (evt: ServerEventPayloads['whenAttackHits'], f: F) => void
  ): this

  /**
   * This event is triggered when the Entity is attacked
   *
   * 受到攻击时: 实体受到攻击时触发该事件
   */
  on(
    eventName: 'whenAttacked',
    handler: (evt: ServerEventPayloads['whenAttacked'], f: F) => void
  ): this

  /**
   * This event is triggered when an Entity is attacked and enters the Vulnerable Status
   *
   * 进入易受打断状态时: 实体被攻击进入易受打断状态时触发该事件
   */
  on(
    eventName: 'whenEnteringAnInterruptibleState',
    handler: (evt: ServerEventPayloads['whenEnteringAnInterruptibleState'], f: F) => void
  ): this

  /**
   * This event is sent to the Component Owner when a Basic Motion Device on the Basic Motion Device Component completes its movement or is disabled
   *
   * 基础运动器停止时: 基础运动器组件上的某个基础运动器完成运动时或被关闭时向组件持有者发送该事件
   */
  on(
    eventName: 'whenBasicMotionDeviceStops',
    handler: (evt: ServerEventPayloads['whenBasicMotionDeviceStops'], f: F) => void
  ): this

  /**
   * When the Pathing Motion Device reaches a Waypoint, it sends this event to the Owner of the Basic Motion Device Component. This event is triggered only if "Send Event on Waypoint Arrival" is enabled in the Waypoint settings
   *
   * 路径到达路点时: 路径运动器到达路点时发送给基础运动器组件的持有者，需要在路点配置中配置“到达路点发送事件”才会触发该事件
   */
  on(
    eventName: 'whenPathReachesWaypoint',
    handler: (evt: ServerEventPayloads['whenPathReachesWaypoint'], f: F) => void
  ): this

  /**
   * This event is triggered when the On-Hit Detection Component's Owner hits other Entities or the Scene
   *
   * 命中检测触发时: 命中检测组件命中其他实体或场景时组件的持有者触发该事件
   */
  on(
    eventName: 'whenOnHitDetectionIsTriggered',
    handler: (evt: ServerEventPayloads['whenOnHitDetectionIsTriggered'], f: F) => void
  ): this

  /**
   * This event is triggered when the Timer reaches the specified time node
   *
   * 定时器触发时: 定时器运行到指定时间节点时，触发该事件
   */
  on(
    eventName: 'whenTimerIsTriggered',
    handler: (evt: ServerEventPayloads['whenTimerIsTriggered'], f: F) => void
  ): this

  /**
   * This event is triggered when the Global Countdown Timer reaches zero; The Global Stopwatch Timer does not trigger this event
   *
   * 全局计时器触发时: 当倒计时的全局计时器计时结束时，会触发该事件; 正计时的全局计时器不会触发该事件
   */
  on(
    eventName: 'whenGlobalTimerIsTriggered',
    handler: (evt: ServerEventPayloads['whenGlobalTimerIsTriggered'], f: F) => void
  ): this

  /**
   * Only UI Controls of the Interactive Button and Item Display types trigger this event; The Node Graph event "UI Control Group Triggered" is sent during Stage runtime when a UI Control Group created through an Interactive Button or an Item Display UI Control is interacted with. This event can only be received by the Node Graph of the Player who triggered the interaction
   *
   * 界面控件组触发时: 只有交互按钮和道具展示类型的界面控件，才会触发本事件; 在关卡运行中，通过交互按钮或道具展示界面控件制作的界面控件组，被执行交互操作会发送节点图事件”界面控件组触发时“，此事件只有触发交互的玩家节点图可以获取
   */
  on(
    eventName: 'whenUiControlGroupIsTriggered',
    handler: (evt: ServerEventPayloads['whenUiControlGroupIsTriggered'], f: F) => void
  ): this

  /**
   * This event is triggered when the Stack Count of a Unit Status changes; This event is triggered when Unit Status effects are applied or removed
   *
   * 单位状态变更时: 单位状态的层数发生变化时，触发该事件; 单位状态的施加以及移除都会触发该事件
   */
  on(
    eventName: 'whenUnitStatusChanges',
    handler: (evt: ServerEventPayloads['whenUnitStatusChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when a Unit Status is removed for any reason or when its Runtime Duration expires
   *
   * 单位状态结束时: 单位状态因为各种原因被移除或因时长结束时触发该事件
   */
  on(
    eventName: 'whenUnitStatusEnds',
    handler: (evt: ServerEventPayloads['whenUnitStatusEnds'], f: F) => void
  ): this

  /**
   * Adds the Unit Status effect [Monitor Elemental Reaction] to the Entity. This event is triggered when the conditions are met
   *
   * 发生元素反应事件时: 为实体添加单位状态效果【监听元素反应】，达成条件会触发该事件
   */
  on(
    eventName: 'whenElementalReactionEventOccurs',
    handler: (evt: ServerEventPayloads['whenElementalReactionEventOccurs'], f: F) => void
  ): this

  /**
   * Adds the Unit Status effect [Add Shield] to the Entity. This event is triggered when the Shield takes damage
   *
   * 护盾受到攻击时: 为实体添加单位状态效果【添加护盾】，受到攻击时触发该事件
   */
  on(
    eventName: 'whenShieldIsAttacked',
    handler: (evt: ServerEventPayloads['whenShieldIsAttacked'], f: F) => void
  ): this

  /**
   * When the active tab is selected, it will send an event to the node graph; The Entity Node Graph configured by the Tab Component will receive this event
   *
   * 选项卡选中时: 生效的选项卡被选中后，会向节点图发送事件; 配置选项卡组件的实体节点图，会接收该事件
   */
  on(
    eventName: 'whenTabIsSelected',
    handler: (evt: ServerEventPayloads['whenTabIsSelected'], f: F) => void
  ): this

  /**
   * Only effective in Classic Aggro Mode; This event is triggered when a Creation enters battle
   *
   * 造物入战时: 仅在经典仇恨模式生效; 造物入战时触发该事件
   */
  on(
    eventName: 'whenCreationEntersCombat',
    handler: (evt: ServerEventPayloads['whenCreationEntersCombat'], f: F) => void
  ): this

  /**
   * Only effective in Classic Aggro Mode; This event is triggered when a Creation leaves battle
   *
   * 造物脱战时: 仅在经典仇恨模式生效; 造物脱战时触发该事件
   */
  on(
    eventName: 'whenCreationLeavesCombat',
    handler: (evt: ServerEventPayloads['whenCreationLeavesCombat'], f: F) => void
  ): this

  /**
   * This event is triggered when a Player's Class Level changes and is sent to the corresponding Player. It can be received in that Class's Node Graph
   *
   * 玩家职业等级变化时: 玩家职业等级变化时触发该事件发送给对应玩家，可以在该职业的职业节点图里收到
   */
  on(
    eventName: 'whenPlayerClassLevelChanges',
    handler: (evt: ServerEventPayloads['whenPlayerClassLevelChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when a Player's Class changes and is sent to the corresponding Player. It can be received in the Node Graph of the new Class
   *
   * 玩家职业更改时: 玩家职业更改时触发该事件发送给对应玩家，可以在更改后职业的职业节点图里收到
   */
  on(
    eventName: 'whenPlayerClassChanges',
    handler: (evt: ServerEventPayloads['whenPlayerClassChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when a Player's Class is removed and sent to the corresponding Player. It can be received in the Node Graph of the previous Class
   *
   * 玩家职业解除时: 玩家职业解除时触发该事件发送给对应玩家，可以在更改前职业的职业节点图里收到
   */
  on(
    eventName: 'whenPlayerClassIsRemoved',
    handler: (evt: ServerEventPayloads['whenPlayerClassIsRemoved'], f: F) => void
  ): this

  /**
   * This event is triggered by the [Notify Server Node Graph] Node in the Skill Node Graph. Up to three strings can be passed in
   *
   * 技能节点调用时: 通过技能节点图的【通知服务器节点图】节点触发，可以传入三个字符串类型的值
   */
  on(
    eventName: 'whenSkillNodeIsCalled',
    handler: (evt: ServerEventPayloads['whenSkillNodeIsCalled'], f: F) => void
  ): this

  /**
   * Available only in Custom Aggro Mode; This event is triggered when the Aggro Target changes; This event can also be triggered when entering or leaving battle
   *
   * 仇恨目标变化时: 仅自定义仇恨模式可用; 仇恨目标发生变化时，触发该事件; 入战和脱战也可以触发该事件
   */
  on(
    eventName: 'whenAggroTargetChanges',
    handler: (evt: ServerEventPayloads['whenAggroTargetChanges'], f: F) => void
  ): this

  /**
   * Available only in Custom Aggro Mode; This event is triggered when the Entity itself enters battle
   *
   * 自身入战时: 仅自定义仇恨模式可用; 实体自身入战时，触发该事件
   */
  on(
    eventName: 'whenSelfEntersCombat',
    handler: (evt: ServerEventPayloads['whenSelfEntersCombat'], f: F) => void
  ): this

  /**
   * Available only in Custom Aggro Mode; This event is triggered when the Entity itself leaves battle
   *
   * 自身脱战时: 仅自定义仇恨模式可用; 实体自身脱战时，触发该事件
   */
  on(
    eventName: 'whenSelfLeavesCombat',
    handler: (evt: ServerEventPayloads['whenSelfLeavesCombat'], f: F) => void
  ): this

  /**
   * Monitors Signal trigger events defined in the Signal Manager; The Signal name to monitor must be selected first
   *
   * 监听信号: 监听已在信号管理器中定义的信号触发事件; 需先选择需要监听的信号名
   */
  on(
    eventName: 'monitorSignal',
    handler: (evt: ServerEventPayloads['monitorSignal'], f: F) => void
  ): this

  /**
   * This event is triggered on the Player's Node Graph when the Player completes the Deck Selector, or when it is forcibly closed due to time constraints; The output parameters report the Deck Selector's result and the corresponding reason
   *
   * 卡牌选择器完成时: 玩家操作完成卡牌选择器/或者因为时间原因强制关闭等，都会给玩家节点图触发本事件; 出参可以通知本次卡牌选择器的结果，和对应原因
   */
  on(
    eventName: 'whenDeckSelectorIsComplete',
    handler: (evt: ServerEventPayloads['whenDeckSelectorIsComplete'], f: F) => void
  ): this

  /**
   * This event can only be mounted by Text Bubble Components and is received by the Entity's Node Graph that completed the dialogue; Completion refers to when the final line of dialogue has finished playing
   *
   * 文本气泡完成时: 该事件仅能被挂载文本气泡组件，且完成对话的实体节点图接收; 完成的含义是最后一句对话播放完成
   */
  on(
    eventName: 'whenTextBubbleIsCompleted',
    handler: (evt: ServerEventPayloads['whenTextBubbleIsCompleted'], f: F) => void
  ): this

  /**
   * This event is triggered when Inventory items are sold in the Shop. The Owner of the Shop Component will receive it
   *
   * 商店出售背包物品时: 商店出售背包物品时触发，商店组件的持有者可收到
   */
  on(
    eventName: 'whenSellingInventoryItemsInTheShop',
    handler: (evt: ServerEventPayloads['whenSellingInventoryItemsInTheShop'], f: F) => void
  ): this

  /**
   * This event is triggered when Custom items are sold in the Shop. The Owner of the Shop Component will receive it
   *
   * 商店出售自定义商品时: 商店出售自定义物品时触发，商店组件的持有者可收到
   */
  on(
    eventName: 'whenCustomShopItemIsSold',
    handler: (evt: ServerEventPayloads['whenCustomShopItemIsSold'], f: F) => void
  ): this

  /**
   * This event is triggered when items are purchased by the Shop. The Owner of the Shop Component will receive it
   *
   * 商店收购道具时: 商店收购道具时触发，商店组件的持有者可收到
   */
  on(
    eventName: 'whenSellingItemsToTheShop',
    handler: (evt: ServerEventPayloads['whenSellingItemsToTheShop'], f: F) => void
  ): this

  /**
   * This event is triggered when Equipment is equipped. The Owner of the Equipment will receive it. Configure this in the Item Node Graph
   *
   * 装备被穿戴时: 装备被穿戴时触发该事件，装备的持有者可以收到，需要配置在道具节点图里
   */
  on(
    eventName: 'whenEquipmentIsEquipped',
    handler: (evt: ServerEventPayloads['whenEquipmentIsEquipped'], f: F) => void
  ): this

  /**
   * This event is triggered when Equipment is unequipped. The Owner of the Equipment will receive it. Configure this in the Item Node Graph
   *
   * 装备被卸下时: 装备被卸下时触发该事件，装备的持有者可以收到，需要配置在道具节点图里
   */
  on(
    eventName: 'whenEquipmentIsUnequipped',
    handler: (evt: ServerEventPayloads['whenEquipmentIsUnequipped'], f: F) => void
  ): this

  /**
   * When Equipment is first obtained and enters the Inventory, it is initialized. The event's output parameters return the unique ID of the Equipment instance. Use this ID to edit the Equipment dynamically. The Owner of the Equipment will receive this event. Configure this in the Item Node Graph
   *
   * 装备初始化时: 当装备首次被获取进入背包时，会进行初始化，此时事件出参会返回装备实例的唯一索引，通过此索引即可对装备进行动态修改。装备的持有者可以收到该事件，需要配置在道具节点图里
   */
  on(
    eventName: 'whenEquipmentIsInitialized',
    handler: (evt: ServerEventPayloads['whenEquipmentIsInitialized'], f: F) => void
  ): this

  /**
   * This event is triggered when Equipment Affix values change. The Owner of the Equipment will receive it. Configure this in the Item Node Graph
   *
   * 装备的词条数值改变时: 装备词条数值改变时触发该事件，装备的持有者可以收到，需要配置在道具节点图里
   */
  on(
    eventName: 'whenEquipmentAffixValueChanges',
    handler: (evt: ServerEventPayloads['whenEquipmentAffixValueChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when an Item is removed from the Inventory (its quantity becomes 0). The Owner of the Inventory Component will receive it
   *
   * 背包道具失去时: 背包内该道具失去，即背包内该道具数量为0时触发该事件，背包组件的持有者可以收到
   */
  on(
    eventName: 'whenItemIsLostFromInventory',
    handler: (evt: ServerEventPayloads['whenItemIsLostFromInventory'], f: F) => void
  ): this

  /**
   * This event is triggered when the quantity of Items in the Inventory changes. The Owner of the Inventory Component will receive it
   *
   * 背包道具数量变化时: 背包道具数量发生变化时触发该事件，背包组件的持有者可以收到
   */
  on(
    eventName: 'whenTheQuantityOfInventoryItemChanges',
    handler: (evt: ServerEventPayloads['whenTheQuantityOfInventoryItemChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when a new Item is added to the Inventory. The Owner of the Inventory Component will receive it. This event is not triggered by quantity-only changes
   *
   * 背包道具新增时: 背包内新增该道具时触发事件，背包组件的持有者可以收到。如果没有新增道具仅有数量变化则不会触发该事件
   */
  on(
    eventName: 'whenItemIsAddedToInventory',
    handler: (evt: ServerEventPayloads['whenItemIsAddedToInventory'], f: F) => void
  ): this

  /**
   * This event is triggered when the amount of Inventory Currency changes. The Owner of the Inventory Component will receive it
   *
   * 背包货币数量变化时: 背包货币数量变化时触发该事件，背包组件的持有者可以收到
   */
  on(
    eventName: 'whenTheQuantityOfInventoryCurrencyChanges',
    handler: (evt: ServerEventPayloads['whenTheQuantityOfInventoryCurrencyChanges'], f: F) => void
  ): this

  /**
   * This event is triggered when an Item in the Inventory is used. The Owner of the Inventory Component will receive it
   *
   * 背包内道具被使用时: 背包内道具被使用时触发该事件，背包组件的持有者可以收到
   */
  on(
    eventName: 'whenItemsInTheInventoryAreUsed',
    handler: (evt: ServerEventPayloads['whenItemsInTheInventoryAreUsed'], f: F) => void
  ): this

  /**
   * When the Send Node Graph Event on Arrival option is enabled for a waypoint in the Patrol template, a Node Graph Event is triggered once the specified conditions are met; This Node Graph Event can only be received by the creation's node graph
   *
   * 造物抵达巡逻路点时: 若在巡逻模板编辑中，勾选了指定路点的到达发送节点图事件选项，则会在满足条件时，收到该节点图事件; 该节点图事件只能造物的节点图收到
   */
  on(
    eventName: 'whenCreationReachesPatrolWaypoint',
    handler: (evt: ServerEventPayloads['whenCreationReachesPatrolWaypoint'], f: F) => void
  ): this

  on<E extends keyof ServerEventPayloads>(
    eventName: E,
    handler: (evt: ServerEventPayloads[E], f: F) => void
  ): this
}
